#!/usr/bin/env node
/* assets/css/site.css 를 만든다 — 전 페이지가 공통으로 읽는 CSS 10개를 한 파일로 잇는다.
   렌더를 막는 요청 수를 10 → 1 로 줄이기 위한 것이고, 원본 파일은 그대로 편집한다.

     node scripts/build-css.js

   ⚠ 아래 목록의 파일을 고친 뒤에는 반드시 다시 실행해야 사이트에 반영된다.
   순서는 기존 <head> 링크 순서 그대로다(뒤에 오는 파일이 같은 선택자를 덮는다).
   페이지 전용 CSS(bmc.css 등)는 여기 넣지 않는다. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'assets', 'css');
const FILES = [
  'inquiry-widget.css',
  'login-modal.css',
  'search-overlay.css',
  'map-links.css',
  'footer.css',
  'reveal.css',
  'typography.css',
  'mobile.css',
  'mobile-overlays.css',
  'mobile-pages.css',
];

const out = FILES.map((f) => {
  const css = fs.readFileSync(path.join(DIR, f), 'utf8').replace(/^﻿/, '');
  return `/* ===== ${f} ===== */\n${css.trim()}\n`;
}).join('\n');

const header = `/* GENERATED by scripts/build-css.js — 직접 고치지 마세요. 원본은 같은 폴더의 개별 파일입니다.\n   build: ${new Date().toISOString().slice(0, 10)} · sources: ${FILES.join(', ')} */\n\n`;
fs.writeFileSync(path.join(DIR, 'site.css'), header + out);
console.log(`assets/css/site.css ← ${FILES.length} files, ${(header + out).length} bytes`);
